### ISSUE TITLE
[FE] feat: (최우선)공통 컴포넌트 구현 - 기타 컴포넌트

### ISSUE THREAD

**Issue by dev4jaehunkim** [codestates-seb/seb42_main_032#11]
### Lead
메인 담당자(FE <이름> 형태로 작성)
서브 담당자는 Assignees로 추가

### 기능 구현을 위해 할 일
- [ ] 화면 정의서를 참고하여 Button 컴포넌트 구현
- [ ] 화면 정의서를 참고하여 Input 컴포넌트 구현
- [ ] 화면 정의서를 참고하여 CheckBox 컴포넌트 구현

### 예상 작업 시간
담당자가 편집으로 예상 작업 시간을 작성

**Comment by ImGyuriKim** [comment]
Chakra 사용으로 따로 재사용할 컴포넌트 생성할 필요성이 없어, 이슈를 닫습니다.
