### ISSUE TITLE
[FE] feat: 예산 조회 기능 구현

### ISSUE THREAD

**Issue by dev4jaehunkim** [codestates-seb/seb42_main_032#80]
### Lead
FE 고재필

### 기능 구현을 위해 할 일
- [x] 총 예산과 현재 사용한 금액을 계산하여 막대 그래프 안에 바 너비 조정
- [x] 카테고리별 예산과 카테고리별 사용 금액을 계산하여 막대 그래프 안에 바 너비 조정
- [x] % 뷰로 볼 때 카테고리별 사용 금액을 계산하여 카테고리 예산의 몇 퍼센트를 사용했는지 표시
- [x] 금액 뷰로 볼 때 카테고리별 사용 금액과 설정된 카테고리별 예산 금액 표시
- [ ] 카테고리별 예산 아이콘은 카테고리 생성 시 지정한 아이콘으로 표시
   - [ ] 백엔드에 POST 요청 시, 아이콘 이름까지 포함하기
- [x] '수정하기' 버튼 클릭 시 예산 설정 페이지로 이동

### 예상 작업 시간
담당자가 편집으로 예상 작업 시간을 작성

**Comment by kohjp** [comment]
카테고리 관리페이지에서는 기본카테고리에서만 예산설정하는걸로 하고 카테고리 추가 수정 삭제는 안되는걸로 하여 이슈 종료함
